export const mockReviewsData = {
  status: "success",
  result: [
    // Property A
    {
      id: 101,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Amazing stay, very clean!",
      reviewCategory: [
        { category: "cleanliness", rating: 10 },
        { category: "communication", rating: 9 },
        { category: "respect_house_rules", rating: 10 },
      ],
      submittedAt: "2025-08-21 22:45:14",
      guestName: "Shane F.",
      listingName: "Shoreditch A",
    },
    {
      id: 102,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Nice place but noisy neighbors.",
      reviewCategory: [
        { category: "cleanliness", rating: 8 },
        { category: "communication", rating: 7 },
        { category: "respect_house_rules", rating: 9 },
      ],
      submittedAt: "2025-09-01 14:32:10",
      guestName: "Alice J.",
      listingName: "Shoreditch A",
    },
    {
      id: 103,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Very comfortable stay.",
      reviewCategory: [
        { category: "cleanliness", rating: 9 },
        { category: "communication", rating: 9 },
        { category: "respect_house_rules", rating: 8 },
      ],
      submittedAt: "2025-09-05 10:12:05",
      guestName: "Bob M.",
      listingName: "Shoreditch A",
    },
    // Property B
    {
      id: 201,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Average experience, some issues with communication.",
      reviewCategory: [
        { category: "cleanliness", rating: 5 },
        { category: "communication", rating: 6 },
        { category: "respect_house_rules", rating: 6 },
      ],
      submittedAt: "2025-08-22 16:20:00",
      guestName: "Clara H.",
      listingName: "Shoreditch B",
    },
    {
      id: 202,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Not very clean, but host was helpful.",
      reviewCategory: [
        { category: "cleanliness", rating: 4 },
        { category: "communication", rating: 8 },
        { category: "respect_house_rules", rating: 7 },
      ],
      submittedAt: "2025-09-03 09:15:00",
      guestName: "David L.",
      listingName: "Shoreditch B",
    },
    {
      id: 203,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Good value for money.",
      reviewCategory: [
        { category: "cleanliness", rating: 6 },
        { category: "communication", rating: 7 },
        { category: "respect_house_rules", rating: 8 },
      ],
      submittedAt: "2025-09-10 18:20:00",
      guestName: "Emma R.",
      listingName: "Shoreditch B",
    },
    // Property C
    {
      id: 301,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Excellent location, very friendly host.",
      reviewCategory: [
        { category: "cleanliness", rating: 9 },
        { category: "communication", rating: 10 },
        { category: "respect_house_rules", rating: 9 },
      ],
      submittedAt: "2025-09-12 12:00:00",
      guestName: "Frank T.",
      listingName: "Shoreditch C",
    },
    {
      id: 302,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Nice apartment but noisy street.",
      reviewCategory: [
        { category: "cleanliness", rating: 7 },
        { category: "communication", rating: 8 },
        { category: "respect_house_rules", rating: 7 },
      ],
      submittedAt: "2025-09-15 15:30:00",
      guestName: "Grace W.",
      listingName: "Shoreditch C",
    },
    {
      id: 303,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Very comfortable stay, recommend to others.",
      reviewCategory: [
        { category: "cleanliness", rating: 9 },
        { category: "communication", rating: 9 },
        { category: "respect_house_rules", rating: 10 },
      ],
      submittedAt: "2025-09-18 20:45:00",
      guestName: "Harry K.",
      listingName: "Shoreditch C",
    },
    // Property D - some null ratings
    {
      id: 401,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Needs improvement in cleanliness.",
      reviewCategory: [
        { category: "cleanliness", rating: 3 },
        { category: "communication", rating: null },
        { category: "respect_house_rules", rating: 6 },
      ],
      submittedAt: "2025-09-20 11:15:00",
      guestName: "Ian P.",
      listingName: "Shoreditch D",
    },
    {
      id: 402,
      type: "host-to-guest",
      status: "published",
      rating: null,
      publicReview: "Good overall, but some issues with rules.",
      reviewCategory: [
        { category: "cleanliness", rating: 5 },
        { category: "communication", rating: 6 },
        { category: "respect_house_rules", rating: null },
      ],
      submittedAt: "2025-09-22 14:40:00",
      guestName: "Judy S.",
      listingName: "Shoreditch D",
    },
    // Property E - no reviews yet (edge case)
  ],
};
